### ISSUE TITLE
Add validated/unvalidated benchmarks

### ISSUE THREAD

**Issue by djkoloski** [djkoloski/rust_serialization_benchmark#13]
This is where we start to get into somewhat murky waters. FlatBuffers supports buffer validation, but the dependency needs to get upgraded to 0.8. Cap'n Proto supports validation, but it's lazy so we would need some way of distinguishing that. Maybe splitting the access/read benchmarks into validated/unvalidated for FlatBuffers and rkyv and leaving the Cap'n Proto results as validated.

**Comment by djkoloski** [comment]
FlatBuffers updated and rkyv implemented in 6b2f8c3be3da776a69b3fc9d1938e7d51d064c6c. It looks like we'd have to manually write validation code for FlatBuffers, so either we do that or omit those benches until they write validation code for the compiler.

**Comment by syrusakbary** [comment]
Is it possible to add the validation benchmark numbers as well to the readme? I'd love to see how different approaches compare to each other!

**Comment by djkoloski** [comment]
Yes, both of the numbers are there. You can hover over anything with an asterisk to get additional context on the specific case.

Only rkyv has validated _and_ unvalidated benchmarks right now. FlatBuffers and Abomonation are unvalidated, and capnp is progressively validated (validated on demand).
