### ISSUE TITLE
Add `speedy` to benchmarks

### ISSUE THREAD

**Issue by praveenperera** [djkoloski/rust_serialization_benchmark#5]
https://github.com/koute/speedy

**Comment by djkoloski** [comment]
Sure, there are a couple others that benchmarks have been requested for. I'll get to it soon but feel free to provide any implementations via pull request if you want to.

**Comment by praveenperera** [comment]
I'm going to see if I can get some time this weekend to do that. Thanks for this by the way, great thorough benchmarks.

**Comment by djkoloski** [comment]
Stealing this one from you, I've been adding a bunch of libraries today. Thanks for offering to help, and thanks for the suggestion to bench `speedy`!

Fixed by 798185cfea8592ed220e15d3e210bbd46954d7cf.

**Comment by praveenperera** [comment]
Great thanks for adding it! 😊
