### ISSUE TITLE
Add tree-buf

### ISSUE THREAD

**Issue by djkoloski** [djkoloski/rust_serialization_benchmark#6]
Repo located [here](https://github.com/That3Percent/tree-buf), requested by reddit

**Comment by djkoloski** [comment]
Blocked by a few issues:

- [ ] https://github.com/That3Percent/tree-buf/issues/16 Signed integer types are not supported, so the minecraft_savedata benchmark can't be run on it
- [ ] The experimental `scratch` API isn't implemented yet, so the benchmarks can't avoid measuring the cost of memory allocation. This would have an effect large enough that I don't think the benchmarks would be accurate.

Mentioning @That3Percent in case they're interested in benchmarking.

**Comment by That3Percent** [comment]
I appreciate this effort. I would love for tree-buf to be included in your benchmark. Unfortunately I've been slammed at work and tree-buf has taken a bit of a backseat for a while. I hope to be able to pick it back up soon.

**Comment by djkoloski** [comment]
Take your time! Self-care is important, the benchmarks will be here waiting for you. 🙂

**Comment by djkoloski** [comment]
Closing this for now, feel free to re-open if you make some forward progress.
