### ISSUE TITLE
Readme updater just recategorized most serializers as zero-copy

### ISSUE THREAD

**Issue by mumbleskates** [djkoloski/rust_serialization_benchmark#91]
It looks like the [last workflow](https://github.com/djkoloski/rust_serialization_benchmark/commit/650f8f5b74d88192014c0001648c6fac190e27f5) just put almost every library into the "zero-copy" category where they have no data. :thinking:

**Comment by mumbleskates** [comment]
actually... it looks like it mostly just swapped everything?

**Comment by djkoloski** [comment]
Looks like #90 unintentionally changed the grouping logic in the README formatter. I committed a fix in 71cfd75515e6de4f97ddd8ad74738c814c8241a1 and kicked a new bench. It should be updated in an hour or so.

**Comment by mumbleskates** [comment]
great, you got to the bottom of that just before i could. it looked like the logic got mostly swapped but not quite, i think you've got it right.
